
К сожалению, я могу помочь только на английском языке. Вот пример быстрого преобразования Фурье на C, используя целочисленный тип (integer):

```
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define PI 3.14159265358979323846

void fft(int n, int *x, int *y)
{
    int i, j, k;
    double c, s, t1, t2;

    for (i = 0, j = 0; i < n; ++i) {
        if (j > i) {
            t1 = x[j];
            x[j] = x[i];
            x[i] = t1;
            t1 = y[j];
            y[j] = y[i];
            y[i] = t1;
        }
        k = n >> 1;
        while (k <= j) {
            j -= k;
            k >>= 1;
        }
        j += k;
    }

    for (i = 0; i < log2(n); ++i) {
        int m = 1 << i;
        int m2 = m << 1;
        for (j = 0; j < m; ++j) {
            int k = j << (log2(n) - i - 1);
            c = cos(-PI * j / m);
            s = sin(-PI * j / m);
            for (k = j; k < n; k += m2) {
                t1 = c * x[k + m] - s * y[k + m];
                t2 = s * x[k + m] + c * y[k + m];
                x[k + m] = x[k] - t1;
                y[k + m] = y[k] - t2;
                x[k] += t1;
                y[k] += t2;
            }
        }
    }
}

int main()
{
    int n = 8;
    int x[] = {1, 0, 1, 0, 1, 0, 1, 0};
    int y[] = {0};

    fft(n, x, y);

    for (int i = 0; i < n; ++i) {
        printf("%d + %di\n", x[i], y[i]);
    }

    return 0;
}
```

Это пример быстрого преобразования Фурье на C для вектора длины 8, состоящего из 0 и 1. При запуске этой программы вы получите преобразование Фурье для данного вектора. Это простой пример, который можно использовать в качестве отправной точки для реализации более сложных преобразований с помощью целочисленных типов.
This message has been generated by Nova - download it for free:
https://novaappai.page.link/8B34sBbfFATZJZ4U6